// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSeveEEY13lXAJm0o--wmX8QedKvLO8yQ',
    appId: '1:147551001214:web:17a118bea3449e91c6d62f',
    messagingSenderId: '147551001214',
    projectId: 'clockwise-2be93',
    authDomain: 'clockwise-2be93.firebaseapp.com',
    storageBucket: 'clockwise-2be93.appspot.com',
    measurementId: 'G-YVFWK4FSXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcOjDnUgE2CVXpX5QQIGZwB5Pwjea4zgg',
    appId: '1:147551001214:android:e711d2bc657deef3c6d62f',
    messagingSenderId: '147551001214',
    projectId: 'clockwise-2be93',
    storageBucket: 'clockwise-2be93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNdxPoseSgsDyibl-L7eXhvDRAvSLnQV8',
    appId: '1:147551001214:ios:ca3e3c21525dfdf8c6d62f',
    messagingSenderId: '147551001214',
    projectId: 'clockwise-2be93',
    storageBucket: 'clockwise-2be93.appspot.com',
    iosBundleId: 'com.example.clockwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNdxPoseSgsDyibl-L7eXhvDRAvSLnQV8',
    appId: '1:147551001214:ios:ca3e3c21525dfdf8c6d62f',
    messagingSenderId: '147551001214',
    projectId: 'clockwise-2be93',
    storageBucket: 'clockwise-2be93.appspot.com',
    iosBundleId: 'com.example.clockwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSeveEEY13lXAJm0o--wmX8QedKvLO8yQ',
    appId: '1:147551001214:web:f7dce75b9349189ec6d62f',
    messagingSenderId: '147551001214',
    projectId: 'clockwise-2be93',
    authDomain: 'clockwise-2be93.firebaseapp.com',
    storageBucket: 'clockwise-2be93.appspot.com',
    measurementId: 'G-5EMP3MEYVB',
  );
}
